/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Apage: typeof import('./src/components/Apage.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BAvatar: typeof import('bootstrap-vue-next/components/BAvatar')['BAvatar']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonToolbar: typeof import('bootstrap-vue-next/components/BButton')['BButtonToolbar']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardGroup: typeof import('bootstrap-vue-next/components/BCard')['BCardGroup']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BInput: typeof import('bootstrap-vue-next/components/BFormInput')['BInput']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BMan: typeof import('./src/components/BMan.vue')['default']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    Centre: typeof import('./src/components/Centre.vue')['default']
    copy: typeof import('./src/components/MusicPlayer copy.vue')['default']
    Guidance: typeof import('./src/components/Guidance.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Maisda: typeof import('./src/components/Maisda.vue')['default']
    Man: typeof import('./src/components/Man.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    'MusicPlayer copy': typeof import('./src/components/MusicPlayer copy.vue')['default']
    MusicPlayer2: typeof import('./src/components/MusicPlayer2.vue')['default']
    OMucsicCard: typeof import('./src/components/OMucsicCard.vue')['default']
    PublicModal: typeof import('./src/components/PublicModal.vue')['default']
    SafeSettings: typeof import('./src/components/SafeSettings.vue')['default']
    SettingTemplate: typeof import('./src/components/SettingTemplate.vue')['default']
    TestTone: typeof import('./src/components/TestTone.vue')['default']
  }
}
