/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementPanel: typeof import('./src/components/AnnouncementPanel.vue')['default']
    Apage: typeof import('./src/components/Apage.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BAvatar: typeof import('bootstrap-vue-next/components/BAvatar')['BAvatar']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BMan: typeof import('./src/components/BMan.vue')['default']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BotCheck: typeof import('./src/instance/bot-check.vue')['default']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    Centre: typeof import('./src/components/Centre.vue')['default']
    copy: typeof import('./src/components/MusicPlayer copy.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Editor: typeof import('./src/editor/Editor.vue')['default']
    EditProfile: typeof import('./src/demos/EditProfile.vue')['default']
    FastEditor: typeof import('./src/editor/FastEditor.vue')['default']
    Fclover: typeof import('./src/components/Fclover.vue')['default']
    Geo: typeof import('./src/instance/geo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Hub: typeof import('./src/components/Hub.vue')['default']
    HubCaro: typeof import('./src/components/HubCaro.vue')['default']
    Maisda: typeof import('./src/components/Maisda.vue')['default']
    Man: typeof import('./src/components/Man.vue')['default']
    Mhy: typeof import('./src/instance/mhy.vue')['default']
    MusicForm: typeof import('./src/instance/MusicForm.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    'MusicPlayer copy': typeof import('./src/components/MusicPlayer copy.vue')['default']
    MusicPlayer2: typeof import('./src/components/MusicPlayer2.vue')['default']
    NewWang: typeof import('./src/editor/newWang.vue')['default']
    PublicModal: typeof import('./src/components/PublicModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RTalk: typeof import('./src/components/RTalk.vue')['default']
    SafeSettings: typeof import('./src/components/SafeSettings.vue')['default']
    SubThem: typeof import('./src/instance/SubThem.vue')['default']
    ToastBoy: typeof import('./src/instance/toastBoy.vue')['default']
  }
}
